python train_mmm.py \
	--processed_data_dir="processed_data_original_120/" \
	--window=130 \
	--batch_size=128 \
	--epochs=5000 \
	--device=1 \
	--entity=rilab-motion \
	--exp_name="final_120_v3" \
	--save_interval=20 \
	--learning_rate=0.0001 \
	--loss_cond_weight=1.5 \
	--loss_pos_weight=0.05 \
	--loss_rot_weight=5.0 \
	--from_idx=9 \
	--target_idx=128 \
	--interpolation='slerp'
