python3 train_tfmodel.py \
    --processed_data_dir='processed_data_walk/' \
	--batch_size=16 \
	--epochs=5000 \
	--device=1 \
	--entity=rilab-motion \
	--exp_name="WALK: bert (llr, lqc0.2, AttAll)" \
	--save_interval=200 \
	--generator_learning_rate=0.00001 \
	--optim_beta1=0.5 \
	--optim_beta2=0.9 \
	--loss_root_weight=0.01 \
	--loss_quat_weight=1.0 \
	--loss_contact_weight=0.2